credentials:
  imap:
    server: 'imap.gmail.com'
    username: 'XXXX@up.edu.ph'
    password: 'XXXXXXXXXXXX'
  telegram:
    token: 'xxxxxx:AAEasasasa28'

email-fetching:
  folder: "INBOX"

send-email:
  subject: 'Bot IS238 - Group 5'