# The below scripts are dedicated to user account credentials configuration.
# For telegram to manage your bot, please remember to update the below credentials with your account information (username, google mail App password, and telegram bot API token).

credentials:
  imap:
    server: 'imap.gmail.com'
    username: 'acsumalinog1@up.edu.ph'
    password: 'vukowxgiewonesav'
  telegram:
    token: '5975368646:AAFD_byJPZlrOzL4PgnQBPGuKksDKISYHV0'

email-fetching:
  folder: "INBOX"

send-email:
  subject: 'Bot IS238 - Group 5'
